/*
API2Cart OpenAPI

API2Cart

API version: 1.1
Contact: contact@api2cart.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProductAddSpecificsInnerBookingDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductAddSpecificsInnerBookingDetails{}

// ProductAddSpecificsInnerBookingDetails struct for ProductAddSpecificsInnerBookingDetails
type ProductAddSpecificsInnerBookingDetails struct {
	Location string `json:"location"`
	Type string `json:"type"`
	SessionDuration *int32 `json:"session_duration,omitempty"`
	SessionGap *int32 `json:"session_gap,omitempty"`
	SessionsCount int32 `json:"sessions_count"`
	TimeStrictValue float32 `json:"time_strict_value"`
	TimeStrictType string `json:"time_strict_type"`
	Availabilities []ProductAddSpecificsInnerBookingDetailsAvailabilitiesInner `json:"availabilities"`
	Overrides []ProductAddSpecificsInnerBookingDetailsOverridesInner `json:"overrides,omitempty"`
}

type _ProductAddSpecificsInnerBookingDetails ProductAddSpecificsInnerBookingDetails

// NewProductAddSpecificsInnerBookingDetails instantiates a new ProductAddSpecificsInnerBookingDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductAddSpecificsInnerBookingDetails(location string, type_ string, sessionsCount int32, timeStrictValue float32, timeStrictType string, availabilities []ProductAddSpecificsInnerBookingDetailsAvailabilitiesInner) *ProductAddSpecificsInnerBookingDetails {
	this := ProductAddSpecificsInnerBookingDetails{}
	this.Location = location
	this.Type = type_
	this.SessionsCount = sessionsCount
	this.TimeStrictValue = timeStrictValue
	this.TimeStrictType = timeStrictType
	this.Availabilities = availabilities
	return &this
}

// NewProductAddSpecificsInnerBookingDetailsWithDefaults instantiates a new ProductAddSpecificsInnerBookingDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductAddSpecificsInnerBookingDetailsWithDefaults() *ProductAddSpecificsInnerBookingDetails {
	this := ProductAddSpecificsInnerBookingDetails{}
	var timeStrictType string = "days"
	this.TimeStrictType = timeStrictType
	return &this
}

// GetLocation returns the Location field value
func (o *ProductAddSpecificsInnerBookingDetails) GetLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *ProductAddSpecificsInnerBookingDetails) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *ProductAddSpecificsInnerBookingDetails) SetLocation(v string) {
	o.Location = v
}

// GetType returns the Type field value
func (o *ProductAddSpecificsInnerBookingDetails) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ProductAddSpecificsInnerBookingDetails) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ProductAddSpecificsInnerBookingDetails) SetType(v string) {
	o.Type = v
}

// GetSessionDuration returns the SessionDuration field value if set, zero value otherwise.
func (o *ProductAddSpecificsInnerBookingDetails) GetSessionDuration() int32 {
	if o == nil || IsNil(o.SessionDuration) {
		var ret int32
		return ret
	}
	return *o.SessionDuration
}

// GetSessionDurationOk returns a tuple with the SessionDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductAddSpecificsInnerBookingDetails) GetSessionDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.SessionDuration) {
		return nil, false
	}
	return o.SessionDuration, true
}

// HasSessionDuration returns a boolean if a field has been set.
func (o *ProductAddSpecificsInnerBookingDetails) HasSessionDuration() bool {
	if o != nil && !IsNil(o.SessionDuration) {
		return true
	}

	return false
}

// SetSessionDuration gets a reference to the given int32 and assigns it to the SessionDuration field.
func (o *ProductAddSpecificsInnerBookingDetails) SetSessionDuration(v int32) {
	o.SessionDuration = &v
}

// GetSessionGap returns the SessionGap field value if set, zero value otherwise.
func (o *ProductAddSpecificsInnerBookingDetails) GetSessionGap() int32 {
	if o == nil || IsNil(o.SessionGap) {
		var ret int32
		return ret
	}
	return *o.SessionGap
}

// GetSessionGapOk returns a tuple with the SessionGap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductAddSpecificsInnerBookingDetails) GetSessionGapOk() (*int32, bool) {
	if o == nil || IsNil(o.SessionGap) {
		return nil, false
	}
	return o.SessionGap, true
}

// HasSessionGap returns a boolean if a field has been set.
func (o *ProductAddSpecificsInnerBookingDetails) HasSessionGap() bool {
	if o != nil && !IsNil(o.SessionGap) {
		return true
	}

	return false
}

// SetSessionGap gets a reference to the given int32 and assigns it to the SessionGap field.
func (o *ProductAddSpecificsInnerBookingDetails) SetSessionGap(v int32) {
	o.SessionGap = &v
}

// GetSessionsCount returns the SessionsCount field value
func (o *ProductAddSpecificsInnerBookingDetails) GetSessionsCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SessionsCount
}

// GetSessionsCountOk returns a tuple with the SessionsCount field value
// and a boolean to check if the value has been set.
func (o *ProductAddSpecificsInnerBookingDetails) GetSessionsCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionsCount, true
}

// SetSessionsCount sets field value
func (o *ProductAddSpecificsInnerBookingDetails) SetSessionsCount(v int32) {
	o.SessionsCount = v
}

// GetTimeStrictValue returns the TimeStrictValue field value
func (o *ProductAddSpecificsInnerBookingDetails) GetTimeStrictValue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TimeStrictValue
}

// GetTimeStrictValueOk returns a tuple with the TimeStrictValue field value
// and a boolean to check if the value has been set.
func (o *ProductAddSpecificsInnerBookingDetails) GetTimeStrictValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeStrictValue, true
}

// SetTimeStrictValue sets field value
func (o *ProductAddSpecificsInnerBookingDetails) SetTimeStrictValue(v float32) {
	o.TimeStrictValue = v
}

// GetTimeStrictType returns the TimeStrictType field value
func (o *ProductAddSpecificsInnerBookingDetails) GetTimeStrictType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TimeStrictType
}

// GetTimeStrictTypeOk returns a tuple with the TimeStrictType field value
// and a boolean to check if the value has been set.
func (o *ProductAddSpecificsInnerBookingDetails) GetTimeStrictTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeStrictType, true
}

// SetTimeStrictType sets field value
func (o *ProductAddSpecificsInnerBookingDetails) SetTimeStrictType(v string) {
	o.TimeStrictType = v
}

// GetAvailabilities returns the Availabilities field value
func (o *ProductAddSpecificsInnerBookingDetails) GetAvailabilities() []ProductAddSpecificsInnerBookingDetailsAvailabilitiesInner {
	if o == nil {
		var ret []ProductAddSpecificsInnerBookingDetailsAvailabilitiesInner
		return ret
	}

	return o.Availabilities
}

// GetAvailabilitiesOk returns a tuple with the Availabilities field value
// and a boolean to check if the value has been set.
func (o *ProductAddSpecificsInnerBookingDetails) GetAvailabilitiesOk() ([]ProductAddSpecificsInnerBookingDetailsAvailabilitiesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Availabilities, true
}

// SetAvailabilities sets field value
func (o *ProductAddSpecificsInnerBookingDetails) SetAvailabilities(v []ProductAddSpecificsInnerBookingDetailsAvailabilitiesInner) {
	o.Availabilities = v
}

// GetOverrides returns the Overrides field value if set, zero value otherwise.
func (o *ProductAddSpecificsInnerBookingDetails) GetOverrides() []ProductAddSpecificsInnerBookingDetailsOverridesInner {
	if o == nil || IsNil(o.Overrides) {
		var ret []ProductAddSpecificsInnerBookingDetailsOverridesInner
		return ret
	}
	return o.Overrides
}

// GetOverridesOk returns a tuple with the Overrides field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductAddSpecificsInnerBookingDetails) GetOverridesOk() ([]ProductAddSpecificsInnerBookingDetailsOverridesInner, bool) {
	if o == nil || IsNil(o.Overrides) {
		return nil, false
	}
	return o.Overrides, true
}

// HasOverrides returns a boolean if a field has been set.
func (o *ProductAddSpecificsInnerBookingDetails) HasOverrides() bool {
	if o != nil && !IsNil(o.Overrides) {
		return true
	}

	return false
}

// SetOverrides gets a reference to the given []ProductAddSpecificsInnerBookingDetailsOverridesInner and assigns it to the Overrides field.
func (o *ProductAddSpecificsInnerBookingDetails) SetOverrides(v []ProductAddSpecificsInnerBookingDetailsOverridesInner) {
	o.Overrides = v
}

func (o ProductAddSpecificsInnerBookingDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductAddSpecificsInnerBookingDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["location"] = o.Location
	toSerialize["type"] = o.Type
	if !IsNil(o.SessionDuration) {
		toSerialize["session_duration"] = o.SessionDuration
	}
	if !IsNil(o.SessionGap) {
		toSerialize["session_gap"] = o.SessionGap
	}
	toSerialize["sessions_count"] = o.SessionsCount
	toSerialize["time_strict_value"] = o.TimeStrictValue
	toSerialize["time_strict_type"] = o.TimeStrictType
	toSerialize["availabilities"] = o.Availabilities
	if !IsNil(o.Overrides) {
		toSerialize["overrides"] = o.Overrides
	}
	return toSerialize, nil
}

func (o *ProductAddSpecificsInnerBookingDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"location",
		"type",
		"sessions_count",
		"time_strict_value",
		"time_strict_type",
		"availabilities",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductAddSpecificsInnerBookingDetails := _ProductAddSpecificsInnerBookingDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductAddSpecificsInnerBookingDetails)

	if err != nil {
		return err
	}

	*o = ProductAddSpecificsInnerBookingDetails(varProductAddSpecificsInnerBookingDetails)

	return err
}

type NullableProductAddSpecificsInnerBookingDetails struct {
	value *ProductAddSpecificsInnerBookingDetails
	isSet bool
}

func (v NullableProductAddSpecificsInnerBookingDetails) Get() *ProductAddSpecificsInnerBookingDetails {
	return v.value
}

func (v *NullableProductAddSpecificsInnerBookingDetails) Set(val *ProductAddSpecificsInnerBookingDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableProductAddSpecificsInnerBookingDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableProductAddSpecificsInnerBookingDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductAddSpecificsInnerBookingDetails(val *ProductAddSpecificsInnerBookingDetails) *NullableProductAddSpecificsInnerBookingDetails {
	return &NullableProductAddSpecificsInnerBookingDetails{value: val, isSet: true}
}

func (v NullableProductAddSpecificsInnerBookingDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductAddSpecificsInnerBookingDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


