/*
API2Cart OpenAPI

API2Cart

API version: 1.1
Contact: contact@api2cart.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Basket type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Basket{}

// Basket struct for Basket
type Basket struct {
	Id *string `json:"id,omitempty"`
	Customer *BaseCustomer `json:"customer,omitempty"`
	BasketUrl NullableString `json:"basket_url,omitempty"`
	CreatedAt NullableA2CDateTime `json:"created_at,omitempty"`
	ModifiedAt NullableA2CDateTime `json:"modified_at,omitempty"`
	Currency *Currency `json:"currency,omitempty"`
	BasketProducts []BasketItem `json:"basket_products,omitempty"`
	AdditionalFields map[string]interface{} `json:"additional_fields,omitempty"`
	CustomFields map[string]interface{} `json:"custom_fields,omitempty"`
}

// NewBasket instantiates a new Basket object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBasket() *Basket {
	this := Basket{}
	return &this
}

// NewBasketWithDefaults instantiates a new Basket object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBasketWithDefaults() *Basket {
	this := Basket{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Basket) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Basket) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Basket) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Basket) SetId(v string) {
	o.Id = &v
}

// GetCustomer returns the Customer field value if set, zero value otherwise.
func (o *Basket) GetCustomer() BaseCustomer {
	if o == nil || IsNil(o.Customer) {
		var ret BaseCustomer
		return ret
	}
	return *o.Customer
}

// GetCustomerOk returns a tuple with the Customer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Basket) GetCustomerOk() (*BaseCustomer, bool) {
	if o == nil || IsNil(o.Customer) {
		return nil, false
	}
	return o.Customer, true
}

// HasCustomer returns a boolean if a field has been set.
func (o *Basket) HasCustomer() bool {
	if o != nil && !IsNil(o.Customer) {
		return true
	}

	return false
}

// SetCustomer gets a reference to the given BaseCustomer and assigns it to the Customer field.
func (o *Basket) SetCustomer(v BaseCustomer) {
	o.Customer = &v
}

// GetBasketUrl returns the BasketUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Basket) GetBasketUrl() string {
	if o == nil || IsNil(o.BasketUrl.Get()) {
		var ret string
		return ret
	}
	return *o.BasketUrl.Get()
}

// GetBasketUrlOk returns a tuple with the BasketUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Basket) GetBasketUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BasketUrl.Get(), o.BasketUrl.IsSet()
}

// HasBasketUrl returns a boolean if a field has been set.
func (o *Basket) HasBasketUrl() bool {
	if o != nil && o.BasketUrl.IsSet() {
		return true
	}

	return false
}

// SetBasketUrl gets a reference to the given NullableString and assigns it to the BasketUrl field.
func (o *Basket) SetBasketUrl(v string) {
	o.BasketUrl.Set(&v)
}
// SetBasketUrlNil sets the value for BasketUrl to be an explicit nil
func (o *Basket) SetBasketUrlNil() {
	o.BasketUrl.Set(nil)
}

// UnsetBasketUrl ensures that no value is present for BasketUrl, not even an explicit nil
func (o *Basket) UnsetBasketUrl() {
	o.BasketUrl.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Basket) GetCreatedAt() A2CDateTime {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret A2CDateTime
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Basket) GetCreatedAtOk() (*A2CDateTime, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Basket) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableA2CDateTime and assigns it to the CreatedAt field.
func (o *Basket) SetCreatedAt(v A2CDateTime) {
	o.CreatedAt.Set(&v)
}
// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *Basket) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *Basket) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetModifiedAt returns the ModifiedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Basket) GetModifiedAt() A2CDateTime {
	if o == nil || IsNil(o.ModifiedAt.Get()) {
		var ret A2CDateTime
		return ret
	}
	return *o.ModifiedAt.Get()
}

// GetModifiedAtOk returns a tuple with the ModifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Basket) GetModifiedAtOk() (*A2CDateTime, bool) {
	if o == nil {
		return nil, false
	}
	return o.ModifiedAt.Get(), o.ModifiedAt.IsSet()
}

// HasModifiedAt returns a boolean if a field has been set.
func (o *Basket) HasModifiedAt() bool {
	if o != nil && o.ModifiedAt.IsSet() {
		return true
	}

	return false
}

// SetModifiedAt gets a reference to the given NullableA2CDateTime and assigns it to the ModifiedAt field.
func (o *Basket) SetModifiedAt(v A2CDateTime) {
	o.ModifiedAt.Set(&v)
}
// SetModifiedAtNil sets the value for ModifiedAt to be an explicit nil
func (o *Basket) SetModifiedAtNil() {
	o.ModifiedAt.Set(nil)
}

// UnsetModifiedAt ensures that no value is present for ModifiedAt, not even an explicit nil
func (o *Basket) UnsetModifiedAt() {
	o.ModifiedAt.Unset()
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *Basket) GetCurrency() Currency {
	if o == nil || IsNil(o.Currency) {
		var ret Currency
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Basket) GetCurrencyOk() (*Currency, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *Basket) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given Currency and assigns it to the Currency field.
func (o *Basket) SetCurrency(v Currency) {
	o.Currency = &v
}

// GetBasketProducts returns the BasketProducts field value if set, zero value otherwise.
func (o *Basket) GetBasketProducts() []BasketItem {
	if o == nil || IsNil(o.BasketProducts) {
		var ret []BasketItem
		return ret
	}
	return o.BasketProducts
}

// GetBasketProductsOk returns a tuple with the BasketProducts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Basket) GetBasketProductsOk() ([]BasketItem, bool) {
	if o == nil || IsNil(o.BasketProducts) {
		return nil, false
	}
	return o.BasketProducts, true
}

// HasBasketProducts returns a boolean if a field has been set.
func (o *Basket) HasBasketProducts() bool {
	if o != nil && !IsNil(o.BasketProducts) {
		return true
	}

	return false
}

// SetBasketProducts gets a reference to the given []BasketItem and assigns it to the BasketProducts field.
func (o *Basket) SetBasketProducts(v []BasketItem) {
	o.BasketProducts = v
}

// GetAdditionalFields returns the AdditionalFields field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Basket) GetAdditionalFields() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.AdditionalFields
}

// GetAdditionalFieldsOk returns a tuple with the AdditionalFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Basket) GetAdditionalFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AdditionalFields) {
		return map[string]interface{}{}, false
	}
	return o.AdditionalFields, true
}

// HasAdditionalFields returns a boolean if a field has been set.
func (o *Basket) HasAdditionalFields() bool {
	if o != nil && !IsNil(o.AdditionalFields) {
		return true
	}

	return false
}

// SetAdditionalFields gets a reference to the given map[string]interface{} and assigns it to the AdditionalFields field.
func (o *Basket) SetAdditionalFields(v map[string]interface{}) {
	o.AdditionalFields = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Basket) GetCustomFields() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Basket) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *Basket) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *Basket) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

func (o Basket) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Basket) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Customer) {
		toSerialize["customer"] = o.Customer
	}
	if o.BasketUrl.IsSet() {
		toSerialize["basket_url"] = o.BasketUrl.Get()
	}
	if o.CreatedAt.IsSet() {
		toSerialize["created_at"] = o.CreatedAt.Get()
	}
	if o.ModifiedAt.IsSet() {
		toSerialize["modified_at"] = o.ModifiedAt.Get()
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.BasketProducts) {
		toSerialize["basket_products"] = o.BasketProducts
	}
	if o.AdditionalFields != nil {
		toSerialize["additional_fields"] = o.AdditionalFields
	}
	if o.CustomFields != nil {
		toSerialize["custom_fields"] = o.CustomFields
	}
	return toSerialize, nil
}

type NullableBasket struct {
	value *Basket
	isSet bool
}

func (v NullableBasket) Get() *Basket {
	return v.value
}

func (v *NullableBasket) Set(val *Basket) {
	v.value = val
	v.isSet = true
}

func (v NullableBasket) IsSet() bool {
	return v.isSet
}

func (v *NullableBasket) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBasket(val *Basket) *NullableBasket {
	return &NullableBasket{value: val, isSet: true}
}

func (v NullableBasket) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBasket) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


