/*
API2Cart OpenAPI

API2Cart

API version: 1.1
Contact: contact@api2cart.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ParamDefinitionFilteringConditionsFilterRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParamDefinitionFilteringConditionsFilterRule{}

// ParamDefinitionFilteringConditionsFilterRule struct for ParamDefinitionFilteringConditionsFilterRule
type ParamDefinitionFilteringConditionsFilterRule struct {
	Field *string `json:"field,omitempty"`
	Operator *string `json:"operator,omitempty"`
	Value *ParamDefinitionFilteringConditionsFilterRuleValue `json:"value,omitempty"`
}

// NewParamDefinitionFilteringConditionsFilterRule instantiates a new ParamDefinitionFilteringConditionsFilterRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParamDefinitionFilteringConditionsFilterRule() *ParamDefinitionFilteringConditionsFilterRule {
	this := ParamDefinitionFilteringConditionsFilterRule{}
	return &this
}

// NewParamDefinitionFilteringConditionsFilterRuleWithDefaults instantiates a new ParamDefinitionFilteringConditionsFilterRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParamDefinitionFilteringConditionsFilterRuleWithDefaults() *ParamDefinitionFilteringConditionsFilterRule {
	this := ParamDefinitionFilteringConditionsFilterRule{}
	return &this
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *ParamDefinitionFilteringConditionsFilterRule) GetField() string {
	if o == nil || IsNil(o.Field) {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParamDefinitionFilteringConditionsFilterRule) GetFieldOk() (*string, bool) {
	if o == nil || IsNil(o.Field) {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *ParamDefinitionFilteringConditionsFilterRule) HasField() bool {
	if o != nil && !IsNil(o.Field) {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *ParamDefinitionFilteringConditionsFilterRule) SetField(v string) {
	o.Field = &v
}

// GetOperator returns the Operator field value if set, zero value otherwise.
func (o *ParamDefinitionFilteringConditionsFilterRule) GetOperator() string {
	if o == nil || IsNil(o.Operator) {
		var ret string
		return ret
	}
	return *o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParamDefinitionFilteringConditionsFilterRule) GetOperatorOk() (*string, bool) {
	if o == nil || IsNil(o.Operator) {
		return nil, false
	}
	return o.Operator, true
}

// HasOperator returns a boolean if a field has been set.
func (o *ParamDefinitionFilteringConditionsFilterRule) HasOperator() bool {
	if o != nil && !IsNil(o.Operator) {
		return true
	}

	return false
}

// SetOperator gets a reference to the given string and assigns it to the Operator field.
func (o *ParamDefinitionFilteringConditionsFilterRule) SetOperator(v string) {
	o.Operator = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ParamDefinitionFilteringConditionsFilterRule) GetValue() ParamDefinitionFilteringConditionsFilterRuleValue {
	if o == nil || IsNil(o.Value) {
		var ret ParamDefinitionFilteringConditionsFilterRuleValue
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParamDefinitionFilteringConditionsFilterRule) GetValueOk() (*ParamDefinitionFilteringConditionsFilterRuleValue, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ParamDefinitionFilteringConditionsFilterRule) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given ParamDefinitionFilteringConditionsFilterRuleValue and assigns it to the Value field.
func (o *ParamDefinitionFilteringConditionsFilterRule) SetValue(v ParamDefinitionFilteringConditionsFilterRuleValue) {
	o.Value = &v
}

func (o ParamDefinitionFilteringConditionsFilterRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParamDefinitionFilteringConditionsFilterRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Field) {
		toSerialize["field"] = o.Field
	}
	if !IsNil(o.Operator) {
		toSerialize["operator"] = o.Operator
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableParamDefinitionFilteringConditionsFilterRule struct {
	value *ParamDefinitionFilteringConditionsFilterRule
	isSet bool
}

func (v NullableParamDefinitionFilteringConditionsFilterRule) Get() *ParamDefinitionFilteringConditionsFilterRule {
	return v.value
}

func (v *NullableParamDefinitionFilteringConditionsFilterRule) Set(val *ParamDefinitionFilteringConditionsFilterRule) {
	v.value = val
	v.isSet = true
}

func (v NullableParamDefinitionFilteringConditionsFilterRule) IsSet() bool {
	return v.isSet
}

func (v *NullableParamDefinitionFilteringConditionsFilterRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParamDefinitionFilteringConditionsFilterRule(val *ParamDefinitionFilteringConditionsFilterRule) *NullableParamDefinitionFilteringConditionsFilterRule {
	return &NullableParamDefinitionFilteringConditionsFilterRule{value: val, isSet: true}
}

func (v NullableParamDefinitionFilteringConditionsFilterRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParamDefinitionFilteringConditionsFilterRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


