/*
API2Cart OpenAPI

API2Cart

API version: 1.1
Contact: contact@api2cart.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CatalogPriceRuleAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogPriceRuleAction{}

// CatalogPriceRuleAction struct for CatalogPriceRuleAction
type CatalogPriceRuleAction struct {
	Scope *string `json:"scope,omitempty"`
	ApplyTo *string `json:"apply_to,omitempty"`
	Type *string `json:"type,omitempty"`
	Quantity *float32 `json:"quantity,omitempty"`
	Value *float32 `json:"value,omitempty"`
	CurrencyCode *string `json:"currency_code,omitempty"`
	IncludeTax *bool `json:"include_tax,omitempty"`
	Conditions []CouponCondition `json:"conditions,omitempty"`
	AdditionalFields map[string]interface{} `json:"additional_fields,omitempty"`
	CustomFields map[string]interface{} `json:"custom_fields,omitempty"`
}

// NewCatalogPriceRuleAction instantiates a new CatalogPriceRuleAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogPriceRuleAction() *CatalogPriceRuleAction {
	this := CatalogPriceRuleAction{}
	return &this
}

// NewCatalogPriceRuleActionWithDefaults instantiates a new CatalogPriceRuleAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogPriceRuleActionWithDefaults() *CatalogPriceRuleAction {
	this := CatalogPriceRuleAction{}
	return &this
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *CatalogPriceRuleAction) GetScope() string {
	if o == nil || IsNil(o.Scope) {
		var ret string
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogPriceRuleAction) GetScopeOk() (*string, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *CatalogPriceRuleAction) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given string and assigns it to the Scope field.
func (o *CatalogPriceRuleAction) SetScope(v string) {
	o.Scope = &v
}

// GetApplyTo returns the ApplyTo field value if set, zero value otherwise.
func (o *CatalogPriceRuleAction) GetApplyTo() string {
	if o == nil || IsNil(o.ApplyTo) {
		var ret string
		return ret
	}
	return *o.ApplyTo
}

// GetApplyToOk returns a tuple with the ApplyTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogPriceRuleAction) GetApplyToOk() (*string, bool) {
	if o == nil || IsNil(o.ApplyTo) {
		return nil, false
	}
	return o.ApplyTo, true
}

// HasApplyTo returns a boolean if a field has been set.
func (o *CatalogPriceRuleAction) HasApplyTo() bool {
	if o != nil && !IsNil(o.ApplyTo) {
		return true
	}

	return false
}

// SetApplyTo gets a reference to the given string and assigns it to the ApplyTo field.
func (o *CatalogPriceRuleAction) SetApplyTo(v string) {
	o.ApplyTo = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CatalogPriceRuleAction) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogPriceRuleAction) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CatalogPriceRuleAction) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CatalogPriceRuleAction) SetType(v string) {
	o.Type = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *CatalogPriceRuleAction) GetQuantity() float32 {
	if o == nil || IsNil(o.Quantity) {
		var ret float32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogPriceRuleAction) GetQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *CatalogPriceRuleAction) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given float32 and assigns it to the Quantity field.
func (o *CatalogPriceRuleAction) SetQuantity(v float32) {
	o.Quantity = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CatalogPriceRuleAction) GetValue() float32 {
	if o == nil || IsNil(o.Value) {
		var ret float32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogPriceRuleAction) GetValueOk() (*float32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CatalogPriceRuleAction) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given float32 and assigns it to the Value field.
func (o *CatalogPriceRuleAction) SetValue(v float32) {
	o.Value = &v
}

// GetCurrencyCode returns the CurrencyCode field value if set, zero value otherwise.
func (o *CatalogPriceRuleAction) GetCurrencyCode() string {
	if o == nil || IsNil(o.CurrencyCode) {
		var ret string
		return ret
	}
	return *o.CurrencyCode
}

// GetCurrencyCodeOk returns a tuple with the CurrencyCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogPriceRuleAction) GetCurrencyCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CurrencyCode) {
		return nil, false
	}
	return o.CurrencyCode, true
}

// HasCurrencyCode returns a boolean if a field has been set.
func (o *CatalogPriceRuleAction) HasCurrencyCode() bool {
	if o != nil && !IsNil(o.CurrencyCode) {
		return true
	}

	return false
}

// SetCurrencyCode gets a reference to the given string and assigns it to the CurrencyCode field.
func (o *CatalogPriceRuleAction) SetCurrencyCode(v string) {
	o.CurrencyCode = &v
}

// GetIncludeTax returns the IncludeTax field value if set, zero value otherwise.
func (o *CatalogPriceRuleAction) GetIncludeTax() bool {
	if o == nil || IsNil(o.IncludeTax) {
		var ret bool
		return ret
	}
	return *o.IncludeTax
}

// GetIncludeTaxOk returns a tuple with the IncludeTax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogPriceRuleAction) GetIncludeTaxOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeTax) {
		return nil, false
	}
	return o.IncludeTax, true
}

// HasIncludeTax returns a boolean if a field has been set.
func (o *CatalogPriceRuleAction) HasIncludeTax() bool {
	if o != nil && !IsNil(o.IncludeTax) {
		return true
	}

	return false
}

// SetIncludeTax gets a reference to the given bool and assigns it to the IncludeTax field.
func (o *CatalogPriceRuleAction) SetIncludeTax(v bool) {
	o.IncludeTax = &v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *CatalogPriceRuleAction) GetConditions() []CouponCondition {
	if o == nil || IsNil(o.Conditions) {
		var ret []CouponCondition
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogPriceRuleAction) GetConditionsOk() ([]CouponCondition, bool) {
	if o == nil || IsNil(o.Conditions) {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *CatalogPriceRuleAction) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given []CouponCondition and assigns it to the Conditions field.
func (o *CatalogPriceRuleAction) SetConditions(v []CouponCondition) {
	o.Conditions = v
}

// GetAdditionalFields returns the AdditionalFields field value if set, zero value otherwise.
func (o *CatalogPriceRuleAction) GetAdditionalFields() map[string]interface{} {
	if o == nil || IsNil(o.AdditionalFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.AdditionalFields
}

// GetAdditionalFieldsOk returns a tuple with the AdditionalFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogPriceRuleAction) GetAdditionalFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AdditionalFields) {
		return map[string]interface{}{}, false
	}
	return o.AdditionalFields, true
}

// HasAdditionalFields returns a boolean if a field has been set.
func (o *CatalogPriceRuleAction) HasAdditionalFields() bool {
	if o != nil && !IsNil(o.AdditionalFields) {
		return true
	}

	return false
}

// SetAdditionalFields gets a reference to the given map[string]interface{} and assigns it to the AdditionalFields field.
func (o *CatalogPriceRuleAction) SetAdditionalFields(v map[string]interface{}) {
	o.AdditionalFields = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *CatalogPriceRuleAction) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogPriceRuleAction) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *CatalogPriceRuleAction) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *CatalogPriceRuleAction) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

func (o CatalogPriceRuleAction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogPriceRuleAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	if !IsNil(o.ApplyTo) {
		toSerialize["apply_to"] = o.ApplyTo
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.CurrencyCode) {
		toSerialize["currency_code"] = o.CurrencyCode
	}
	if !IsNil(o.IncludeTax) {
		toSerialize["include_tax"] = o.IncludeTax
	}
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	if !IsNil(o.AdditionalFields) {
		toSerialize["additional_fields"] = o.AdditionalFields
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}
	return toSerialize, nil
}

type NullableCatalogPriceRuleAction struct {
	value *CatalogPriceRuleAction
	isSet bool
}

func (v NullableCatalogPriceRuleAction) Get() *CatalogPriceRuleAction {
	return v.value
}

func (v *NullableCatalogPriceRuleAction) Set(val *CatalogPriceRuleAction) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogPriceRuleAction) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogPriceRuleAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogPriceRuleAction(val *CatalogPriceRuleAction) *NullableCatalogPriceRuleAction {
	return &NullableCatalogPriceRuleAction{value: val, isSet: true}
}

func (v NullableCatalogPriceRuleAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogPriceRuleAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


