/*
API2Cart OpenAPI

API2Cart

API version: 1.1
Contact: contact@api2cart.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// ParamDefinitionFilteringConditionsFilterCondition - struct for ParamDefinitionFilteringConditionsFilterCondition
type ParamDefinitionFilteringConditionsFilterCondition struct {
	ParamDefinitionFilteringConditionsFilterGroup *ParamDefinitionFilteringConditionsFilterGroup
	ParamDefinitionFilteringConditionsFilterRule *ParamDefinitionFilteringConditionsFilterRule
}

// ParamDefinitionFilteringConditionsFilterGroupAsParamDefinitionFilteringConditionsFilterCondition is a convenience function that returns ParamDefinitionFilteringConditionsFilterGroup wrapped in ParamDefinitionFilteringConditionsFilterCondition
func ParamDefinitionFilteringConditionsFilterGroupAsParamDefinitionFilteringConditionsFilterCondition(v *ParamDefinitionFilteringConditionsFilterGroup) ParamDefinitionFilteringConditionsFilterCondition {
	return ParamDefinitionFilteringConditionsFilterCondition{
		ParamDefinitionFilteringConditionsFilterGroup: v,
	}
}

// ParamDefinitionFilteringConditionsFilterRuleAsParamDefinitionFilteringConditionsFilterCondition is a convenience function that returns ParamDefinitionFilteringConditionsFilterRule wrapped in ParamDefinitionFilteringConditionsFilterCondition
func ParamDefinitionFilteringConditionsFilterRuleAsParamDefinitionFilteringConditionsFilterCondition(v *ParamDefinitionFilteringConditionsFilterRule) ParamDefinitionFilteringConditionsFilterCondition {
	return ParamDefinitionFilteringConditionsFilterCondition{
		ParamDefinitionFilteringConditionsFilterRule: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ParamDefinitionFilteringConditionsFilterCondition) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ParamDefinitionFilteringConditionsFilterGroup
	err = newStrictDecoder(data).Decode(&dst.ParamDefinitionFilteringConditionsFilterGroup)
	if err == nil {
		jsonParamDefinitionFilteringConditionsFilterGroup, _ := json.Marshal(dst.ParamDefinitionFilteringConditionsFilterGroup)
		if string(jsonParamDefinitionFilteringConditionsFilterGroup) == "{}" { // empty struct
			dst.ParamDefinitionFilteringConditionsFilterGroup = nil
		} else {
			if err = validator.Validate(dst.ParamDefinitionFilteringConditionsFilterGroup); err != nil {
				dst.ParamDefinitionFilteringConditionsFilterGroup = nil
			} else {
				match++
			}
		}
	} else {
		dst.ParamDefinitionFilteringConditionsFilterGroup = nil
	}

	// try to unmarshal data into ParamDefinitionFilteringConditionsFilterRule
	err = newStrictDecoder(data).Decode(&dst.ParamDefinitionFilteringConditionsFilterRule)
	if err == nil {
		jsonParamDefinitionFilteringConditionsFilterRule, _ := json.Marshal(dst.ParamDefinitionFilteringConditionsFilterRule)
		if string(jsonParamDefinitionFilteringConditionsFilterRule) == "{}" { // empty struct
			dst.ParamDefinitionFilteringConditionsFilterRule = nil
		} else {
			if err = validator.Validate(dst.ParamDefinitionFilteringConditionsFilterRule); err != nil {
				dst.ParamDefinitionFilteringConditionsFilterRule = nil
			} else {
				match++
			}
		}
	} else {
		dst.ParamDefinitionFilteringConditionsFilterRule = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ParamDefinitionFilteringConditionsFilterGroup = nil
		dst.ParamDefinitionFilteringConditionsFilterRule = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ParamDefinitionFilteringConditionsFilterCondition)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ParamDefinitionFilteringConditionsFilterCondition)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ParamDefinitionFilteringConditionsFilterCondition) MarshalJSON() ([]byte, error) {
	if src.ParamDefinitionFilteringConditionsFilterGroup != nil {
		return json.Marshal(&src.ParamDefinitionFilteringConditionsFilterGroup)
	}

	if src.ParamDefinitionFilteringConditionsFilterRule != nil {
		return json.Marshal(&src.ParamDefinitionFilteringConditionsFilterRule)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ParamDefinitionFilteringConditionsFilterCondition) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ParamDefinitionFilteringConditionsFilterGroup != nil {
		return obj.ParamDefinitionFilteringConditionsFilterGroup
	}

	if obj.ParamDefinitionFilteringConditionsFilterRule != nil {
		return obj.ParamDefinitionFilteringConditionsFilterRule
	}

	// all schemas are nil
	return nil
}

type NullableParamDefinitionFilteringConditionsFilterCondition struct {
	value *ParamDefinitionFilteringConditionsFilterCondition
	isSet bool
}

func (v NullableParamDefinitionFilteringConditionsFilterCondition) Get() *ParamDefinitionFilteringConditionsFilterCondition {
	return v.value
}

func (v *NullableParamDefinitionFilteringConditionsFilterCondition) Set(val *ParamDefinitionFilteringConditionsFilterCondition) {
	v.value = val
	v.isSet = true
}

func (v NullableParamDefinitionFilteringConditionsFilterCondition) IsSet() bool {
	return v.isSet
}

func (v *NullableParamDefinitionFilteringConditionsFilterCondition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParamDefinitionFilteringConditionsFilterCondition(val *ParamDefinitionFilteringConditionsFilterCondition) *NullableParamDefinitionFilteringConditionsFilterCondition {
	return &NullableParamDefinitionFilteringConditionsFilterCondition{value: val, isSet: true}
}

func (v NullableParamDefinitionFilteringConditionsFilterCondition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParamDefinitionFilteringConditionsFilterCondition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


