/*
API2Cart OpenAPI

API2Cart

API version: 1.1
Contact: contact@api2cart.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrderShipmentTrackingAdd type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderShipmentTrackingAdd{}

// OrderShipmentTrackingAdd struct for OrderShipmentTrackingAdd
type OrderShipmentTrackingAdd struct {
	// Defines the order id
	OrderId *string `json:"order_id,omitempty"`
	// Shipment id indicates the number of delivery
	ShipmentId string `json:"shipment_id"`
	// Defines tracking carrier id
	CarrierId *string `json:"carrier_id,omitempty"`
	// Store Id
	StoreId *string `json:"store_id,omitempty"`
	// Defines name of the company which provides shipment tracking
	TrackingProvider *string `json:"tracking_provider,omitempty"`
	// Defines tracking number
	TrackingNumber string `json:"tracking_number"`
	// Defines custom tracking link
	TrackingLink *string `json:"tracking_link,omitempty"`
	// Send notifications to customer after tracking was created
	SendNotifications *bool `json:"send_notifications,omitempty"`
	// A unique identifier associated with a specific request. Repeated requests with the same <strong>idempotency_key</strong> return a cached response without re-executing the business logic. <strong>Please note that the cache lifetime is 15 minutes.</strong>
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
}

type _OrderShipmentTrackingAdd OrderShipmentTrackingAdd

// NewOrderShipmentTrackingAdd instantiates a new OrderShipmentTrackingAdd object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderShipmentTrackingAdd(shipmentId string, trackingNumber string) *OrderShipmentTrackingAdd {
	this := OrderShipmentTrackingAdd{}
	this.ShipmentId = shipmentId
	this.TrackingNumber = trackingNumber
	var sendNotifications bool = false
	this.SendNotifications = &sendNotifications
	return &this
}

// NewOrderShipmentTrackingAddWithDefaults instantiates a new OrderShipmentTrackingAdd object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderShipmentTrackingAddWithDefaults() *OrderShipmentTrackingAdd {
	this := OrderShipmentTrackingAdd{}
	var sendNotifications bool = false
	this.SendNotifications = &sendNotifications
	return &this
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *OrderShipmentTrackingAdd) GetOrderId() string {
	if o == nil || IsNil(o.OrderId) {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderShipmentTrackingAdd) GetOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrderId) {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *OrderShipmentTrackingAdd) HasOrderId() bool {
	if o != nil && !IsNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *OrderShipmentTrackingAdd) SetOrderId(v string) {
	o.OrderId = &v
}

// GetShipmentId returns the ShipmentId field value
func (o *OrderShipmentTrackingAdd) GetShipmentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShipmentId
}

// GetShipmentIdOk returns a tuple with the ShipmentId field value
// and a boolean to check if the value has been set.
func (o *OrderShipmentTrackingAdd) GetShipmentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShipmentId, true
}

// SetShipmentId sets field value
func (o *OrderShipmentTrackingAdd) SetShipmentId(v string) {
	o.ShipmentId = v
}

// GetCarrierId returns the CarrierId field value if set, zero value otherwise.
func (o *OrderShipmentTrackingAdd) GetCarrierId() string {
	if o == nil || IsNil(o.CarrierId) {
		var ret string
		return ret
	}
	return *o.CarrierId
}

// GetCarrierIdOk returns a tuple with the CarrierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderShipmentTrackingAdd) GetCarrierIdOk() (*string, bool) {
	if o == nil || IsNil(o.CarrierId) {
		return nil, false
	}
	return o.CarrierId, true
}

// HasCarrierId returns a boolean if a field has been set.
func (o *OrderShipmentTrackingAdd) HasCarrierId() bool {
	if o != nil && !IsNil(o.CarrierId) {
		return true
	}

	return false
}

// SetCarrierId gets a reference to the given string and assigns it to the CarrierId field.
func (o *OrderShipmentTrackingAdd) SetCarrierId(v string) {
	o.CarrierId = &v
}

// GetStoreId returns the StoreId field value if set, zero value otherwise.
func (o *OrderShipmentTrackingAdd) GetStoreId() string {
	if o == nil || IsNil(o.StoreId) {
		var ret string
		return ret
	}
	return *o.StoreId
}

// GetStoreIdOk returns a tuple with the StoreId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderShipmentTrackingAdd) GetStoreIdOk() (*string, bool) {
	if o == nil || IsNil(o.StoreId) {
		return nil, false
	}
	return o.StoreId, true
}

// HasStoreId returns a boolean if a field has been set.
func (o *OrderShipmentTrackingAdd) HasStoreId() bool {
	if o != nil && !IsNil(o.StoreId) {
		return true
	}

	return false
}

// SetStoreId gets a reference to the given string and assigns it to the StoreId field.
func (o *OrderShipmentTrackingAdd) SetStoreId(v string) {
	o.StoreId = &v
}

// GetTrackingProvider returns the TrackingProvider field value if set, zero value otherwise.
func (o *OrderShipmentTrackingAdd) GetTrackingProvider() string {
	if o == nil || IsNil(o.TrackingProvider) {
		var ret string
		return ret
	}
	return *o.TrackingProvider
}

// GetTrackingProviderOk returns a tuple with the TrackingProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderShipmentTrackingAdd) GetTrackingProviderOk() (*string, bool) {
	if o == nil || IsNil(o.TrackingProvider) {
		return nil, false
	}
	return o.TrackingProvider, true
}

// HasTrackingProvider returns a boolean if a field has been set.
func (o *OrderShipmentTrackingAdd) HasTrackingProvider() bool {
	if o != nil && !IsNil(o.TrackingProvider) {
		return true
	}

	return false
}

// SetTrackingProvider gets a reference to the given string and assigns it to the TrackingProvider field.
func (o *OrderShipmentTrackingAdd) SetTrackingProvider(v string) {
	o.TrackingProvider = &v
}

// GetTrackingNumber returns the TrackingNumber field value
func (o *OrderShipmentTrackingAdd) GetTrackingNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TrackingNumber
}

// GetTrackingNumberOk returns a tuple with the TrackingNumber field value
// and a boolean to check if the value has been set.
func (o *OrderShipmentTrackingAdd) GetTrackingNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrackingNumber, true
}

// SetTrackingNumber sets field value
func (o *OrderShipmentTrackingAdd) SetTrackingNumber(v string) {
	o.TrackingNumber = v
}

// GetTrackingLink returns the TrackingLink field value if set, zero value otherwise.
func (o *OrderShipmentTrackingAdd) GetTrackingLink() string {
	if o == nil || IsNil(o.TrackingLink) {
		var ret string
		return ret
	}
	return *o.TrackingLink
}

// GetTrackingLinkOk returns a tuple with the TrackingLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderShipmentTrackingAdd) GetTrackingLinkOk() (*string, bool) {
	if o == nil || IsNil(o.TrackingLink) {
		return nil, false
	}
	return o.TrackingLink, true
}

// HasTrackingLink returns a boolean if a field has been set.
func (o *OrderShipmentTrackingAdd) HasTrackingLink() bool {
	if o != nil && !IsNil(o.TrackingLink) {
		return true
	}

	return false
}

// SetTrackingLink gets a reference to the given string and assigns it to the TrackingLink field.
func (o *OrderShipmentTrackingAdd) SetTrackingLink(v string) {
	o.TrackingLink = &v
}

// GetSendNotifications returns the SendNotifications field value if set, zero value otherwise.
func (o *OrderShipmentTrackingAdd) GetSendNotifications() bool {
	if o == nil || IsNil(o.SendNotifications) {
		var ret bool
		return ret
	}
	return *o.SendNotifications
}

// GetSendNotificationsOk returns a tuple with the SendNotifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderShipmentTrackingAdd) GetSendNotificationsOk() (*bool, bool) {
	if o == nil || IsNil(o.SendNotifications) {
		return nil, false
	}
	return o.SendNotifications, true
}

// HasSendNotifications returns a boolean if a field has been set.
func (o *OrderShipmentTrackingAdd) HasSendNotifications() bool {
	if o != nil && !IsNil(o.SendNotifications) {
		return true
	}

	return false
}

// SetSendNotifications gets a reference to the given bool and assigns it to the SendNotifications field.
func (o *OrderShipmentTrackingAdd) SetSendNotifications(v bool) {
	o.SendNotifications = &v
}

// GetIdempotencyKey returns the IdempotencyKey field value if set, zero value otherwise.
func (o *OrderShipmentTrackingAdd) GetIdempotencyKey() string {
	if o == nil || IsNil(o.IdempotencyKey) {
		var ret string
		return ret
	}
	return *o.IdempotencyKey
}

// GetIdempotencyKeyOk returns a tuple with the IdempotencyKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderShipmentTrackingAdd) GetIdempotencyKeyOk() (*string, bool) {
	if o == nil || IsNil(o.IdempotencyKey) {
		return nil, false
	}
	return o.IdempotencyKey, true
}

// HasIdempotencyKey returns a boolean if a field has been set.
func (o *OrderShipmentTrackingAdd) HasIdempotencyKey() bool {
	if o != nil && !IsNil(o.IdempotencyKey) {
		return true
	}

	return false
}

// SetIdempotencyKey gets a reference to the given string and assigns it to the IdempotencyKey field.
func (o *OrderShipmentTrackingAdd) SetIdempotencyKey(v string) {
	o.IdempotencyKey = &v
}

func (o OrderShipmentTrackingAdd) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderShipmentTrackingAdd) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrderId) {
		toSerialize["order_id"] = o.OrderId
	}
	toSerialize["shipment_id"] = o.ShipmentId
	if !IsNil(o.CarrierId) {
		toSerialize["carrier_id"] = o.CarrierId
	}
	if !IsNil(o.StoreId) {
		toSerialize["store_id"] = o.StoreId
	}
	if !IsNil(o.TrackingProvider) {
		toSerialize["tracking_provider"] = o.TrackingProvider
	}
	toSerialize["tracking_number"] = o.TrackingNumber
	if !IsNil(o.TrackingLink) {
		toSerialize["tracking_link"] = o.TrackingLink
	}
	if !IsNil(o.SendNotifications) {
		toSerialize["send_notifications"] = o.SendNotifications
	}
	if !IsNil(o.IdempotencyKey) {
		toSerialize["idempotency_key"] = o.IdempotencyKey
	}
	return toSerialize, nil
}

func (o *OrderShipmentTrackingAdd) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"shipment_id",
		"tracking_number",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderShipmentTrackingAdd := _OrderShipmentTrackingAdd{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrderShipmentTrackingAdd)

	if err != nil {
		return err
	}

	*o = OrderShipmentTrackingAdd(varOrderShipmentTrackingAdd)

	return err
}

type NullableOrderShipmentTrackingAdd struct {
	value *OrderShipmentTrackingAdd
	isSet bool
}

func (v NullableOrderShipmentTrackingAdd) Get() *OrderShipmentTrackingAdd {
	return v.value
}

func (v *NullableOrderShipmentTrackingAdd) Set(val *OrderShipmentTrackingAdd) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderShipmentTrackingAdd) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderShipmentTrackingAdd) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderShipmentTrackingAdd(val *OrderShipmentTrackingAdd) *NullableOrderShipmentTrackingAdd {
	return &NullableOrderShipmentTrackingAdd{value: val, isSet: true}
}

func (v NullableOrderShipmentTrackingAdd) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderShipmentTrackingAdd) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


